# Supabase Project Configuration
project_id = "punsyovoraatcsigqpuj"

[functions.send-application-ack]
verify_jwt = false

[functions.send-newsletter-ack]
verify_jwt = false

[functions.create-booking-and-calendar]
verify_jwt = false
